#!/usr/bin/env bash
# a script to run scp through args

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	scp -o StrictHostKeyChecking=no "$4" "$1" "$3@$2":~
fi
