#!/usr/bin/env bash
# a script to run scp through args

if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	filepath="$1"
	ip_add="$2"
	username="$3"
	ssh_key="$4"

	scp -i "$ssh_key" "$filepath" "$username"@"$ip_add":~/
fi


