#!/usr/bin/env bash
# a script to install and configure nginx with redirect
sudo apt -y update
sudo apt -y install nginx
sudo bash -c ' echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
