#!/usr/bin/env bash
# a script to install and configure nginx
sudo apt -y update
sudo apt -y install nginx
sudo bash -c ' echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i 'listen [::]:80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
