#!/usr/bin/env bash
# a script to install and configure haproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo cat >> /etc/haproxy/haproxy.cfg <<EOF
frontend http
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
    	balance roundrobin
    	server 531382-web-01 100.25.41.53:80 check
    	server 531382-web-02 52.3.253.7:80 check
EOF
sudo sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo service haproxy restart
