#!/usr/bin/env bash
# script to replace config by default
string="8080 default_server"
new_string="80 default_server"
sed -i "s/$string/$new_string/" /etc/nginx/sites-enabled/default
service nginx restart
