#!/usr/bin/env bash
# who my pid?
# shellcheck disable=SC2078
sig_term()
{
	echo "I hate the kill command"
	rm -f /var/run/myscript.pid
	exit 0
}

sig_int()
{
	echo "Y U no love me?!"
}

sig_quit()
{
	rm -f /var/run/myscript.pid
	exit 0
}

trap "sig_term" SIGTERM
trap "sig_int" SIGINT
trap "sig_quit" SIGQUIT

echo $$ > /var/run/myscript.pid

while [ True ]
do
	echo "To infinity and beyond"
	sleep 2
done
