#!/usr/bin/env bash
# who my pid?

start()
{
	./manage_my_process & echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop()
{
	pkill manage_my_process
	rm -f /var/run/my_process.pid
	echo "manage_my_process stopped"
}

restart()
{
	stop
	start
	echo "manage_my_process restarted"
}

case $1 in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		exit 1
esac

exit 0
