#!/usr/bin/env bash
# file op
while IFS=: read -r uname pass uid gid info home cmd
do
    echo "The user $uname is part of the $gid gang, lives in $home and rides $cmd. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd
