#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ $i -lt 21 ]
do
	if [ $i -eq 5 ]
	then
		echo "bad luck from China"
	elif [ $i -eq 10 ]
	then
		echo "bad luck from Japan"
	elif [ $i -eq 18 ]
	then
		echo "bad luck from Italy"
	fi
	echo $i
	(( i++ ))
done
