#!/usr/bin/env bash
# setup ufw
sudo apt-get update
sudo apt-get install ufw -y
echo "y" | sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 43/tcp
sudo ufw status verbose
