#!/usr/bin/env bash
#fix server
sudo pkill apache2
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/#user www-data;/#user nginx;/' /etc/nginx/nginx.conf
sudo chmod 644 -R /etc/nginx/nginx.conf
sudo service nginx restart
