#!/usr/bin/env bash
#reboot gunicorn gracefully
MASTER_PID=$(pgrep -f 'gunicorn' | head -n 1)

# Check if the master process PID was found
if [ -z "$MASTER_PID" ]; then
  echo "Gunicorn master process not found."
  exit 1
fi

# Send the HUP signal to the master process
kill -HUP "$MASTER_PID"
